# Shared lib for the demo scripts. Source this from each demo step.
#
# Required env (export before sourcing or it'll fail loudly):
#   AGENT_SHARED_SECRET — same value the deployed agent service runs with
#
# Optional env:
#   AGENT_URL — defaults to the deployed Railway URL

set -e

: "${AGENT_URL:=https://copilot-agent-production-ba87.up.railway.app}"

if [ -z "${AGENT_SHARED_SECRET:-}" ]; then
  echo "✘ AGENT_SHARED_SECRET is not set." >&2
  echo "  Run:  export AGENT_SHARED_SECRET=<value>" >&2
  echo "  (Same secret the deployed copilot-agent service is running with.)" >&2
  return 1 2>/dev/null || exit 1
fi

# Patient UUIDs on the deployed OpenEMR demo data. These are stable —
# auto-generated by OpenEMR on first FHIR access, persisted in MariaDB.
FARRAH_UUID="a1ab5594-20c8-4363-be30-75d287be735d"   # 2 active meds
TED_UUID="a1ab5594-20a2-4c30-b8d0-f7a153422786"      # 0 active meds
EDUARDO_UUID="a1ab5594-20c6-40ec-b85b-7dd2c4c728ca"  # 0 active meds

# Locate node (the user has it at /c/Program Files/nodejs/ on Windows)
if ! command -v node >/dev/null 2>&1; then
  if [ -x "/c/Program Files/nodejs/node.exe" ]; then
    export PATH="/c/Program Files/nodejs:$PATH"
  else
    echo "✘ node not on PATH — needed for HMAC token mint." >&2
    return 1 2>/dev/null || exit 1
  fi
fi

# Mint an HMAC token bound to a patient_uuid. Format must match
# agent-service/src/copilot/context/patient.py byte-for-byte.
mint_token() {
  local patient_uuid="$1"
  AGENT_SHARED_SECRET="$AGENT_SHARED_SECRET" PATIENT_UUID="$patient_uuid" node -e '
    const crypto = require("crypto");
    const SECRET = process.env.AGENT_SHARED_SECRET;
    const payload = {
      user_id: 1,
      patient_uuid: process.env.PATIENT_UUID,
      encounter_uuid: null,
      issued_at: Math.floor(Date.now() / 1000),
      nonce: crypto.randomBytes(8).toString("hex"),
    };
    const json = JSON.stringify(payload);
    const b64 = Buffer.from(json).toString("base64url");
    const sig = crypto.createHmac("sha256", SECRET).update(b64).digest("hex");
    process.stdout.write(b64 + "." + sig);
  '
}

# Pretty-print the agent's JSON response in human-readable form for
# the demo. Reads JSON on stdin.
pretty_response() {
  node -e '
    let raw = "";
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", c => raw += c);
    process.stdin.on("end", () => {
      let data;
      try { data = JSON.parse(raw); }
      catch { console.log(raw); return; }
      const dim = "\x1b[2m", reset = "\x1b[0m", bold = "\x1b[1m";
      const green = "\x1b[32m", red = "\x1b[31m", cyan = "\x1b[36m";
      console.log("");
      console.log(bold + "─── Response " + "─".repeat(60) + reset);
      console.log("");
      console.log(data.text || "(no text)");
      console.log("");
      console.log(dim + "─── Metadata " + "─".repeat(60) + reset);
      const refused = data.refused === true;
      const refusedColor = refused ? red : green;
      console.log(`  ${dim}refused:${reset} ${refusedColor}${refused}${reset}`);
      if (data.refusal_reason) {
        console.log(`  ${dim}reason:${reset}  ${data.refusal_reason}`);
      }
      const sources = data.sources || [];
      console.log(`  ${dim}sources:${reset} ${sources.length} citation(s)`);
      sources.forEach(s => console.log(`    ${cyan}${s}${reset}`));
      console.log("");
    });
  '
}

# Post a chat turn. $1 = patient_uuid, $2 = message.
# Times the round trip and pretty-prints the response.
post_chat() {
  local patient_uuid="$1"
  local message="$2"
  local token
  token=$(mint_token "$patient_uuid")

  echo ""
  echo -e "\x1b[1m─── Request \x1b[0m$(printf '─%.0s' $(seq 1 60))"
  echo -e "  \x1b[2mpatient:\x1b[0m  ${patient_uuid:0:8}…"
  echo -e "  \x1b[2mmessage:\x1b[0m  $message"

  local started elapsed http_status body
  started=$(date +%s%3N)
  body=$(curl -sS --max-time 90 -X POST "$AGENT_URL/agent/chat" \
    -H "Authorization: Bearer $token" \
    -H "Content-Type: application/json" \
    -w '\n__HTTP_STATUS__%{http_code}' \
    -d "$(node -e 'process.stdout.write(JSON.stringify({message: process.argv[1], history: []}))' "$message")")
  elapsed=$(( $(date +%s%3N) - started ))
  http_status=$(echo "$body" | grep -oE '__HTTP_STATUS__[0-9]+' | tail -1 | sed 's/__HTTP_STATUS__//')
  body=$(echo "$body" | sed -E '/^__HTTP_STATUS__[0-9]+$/d')

  echo -e "  \x1b[2mhttp:\x1b[0m     $http_status   \x1b[2mlatency:\x1b[0m $elapsed ms"

  echo "$body" | pretty_response
}
